/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package json.jav;

/**
 *
 * @author Mario
 */
public class INTERFAS extends javax.swing.JFrame {
CPE CP = new CPE();
CPE_DETALLE DETALLE =new CPE_DETALLE();
    /**
     * Creates new form INTERFAS
     */
    public INTERFAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        t_1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        t_1.setText("t_1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(t_1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addGap(57, 57, 57)
                .addComponent(t_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   CP.setTIPO_OPERACION(" joder");
   //t_1.setText(CP.getTIPO_OPERACION());
   INTERFAS2 V = new INTERFAS2();
   V.setVisible(true);
   
CP.setTIPO_OPERACION             ("");                               
CP.setTOTAL_GRAVADAS             (12);                               
CP.setSUB_TOTAL                  (12);                               
CP.setTOTAL_IGV                  (12.5);                               
CP.setTOTAL_ISC                  (12.5);                               
CP.setTOTAL_OTR_IMP              (12.5);                               
CP.setTOTAL                      (12.5);                               
CP.setTOTAL_LETRAS               ("");                               
CP.setNRO_GUIA_REMISION          ("");                               
CP.setCOD_GUIA_REMISION          ("");                               
CP.setNRO_OTR_COMPROBANTE        ("");                               
CP.setCOD_OTR_COMPROBANTE        ("");                               
CP.setNRO_COMPROBANTE            ("");                               
CP.setFECHA_DOCUMENTO            ("");                               
CP.setCOD_TIPO_DOCUMENTO         ("");                               
CP.setCOD_MONEDA                 ("");                               
//==============PARA PLAA DE VEHICULO=============
       
CP.setPLACA_VEHICULO             ("");                               
//========================DATOS NOTA CREDITO/NOTA DEBITO==
CP.setTIPO_COMPROBANTE_MODIFICA  ("");                               
CP.setNRO_DOCUMENTO_MODIFICA     ("");                               
CP.setCOD_TIPO_MOTIVO            ("");                               
CP.setDESCRIPCION_MOTIVO         ("");                               
//========================DATOS DEL CIENTE================
CP.setNRO_DOCUMENTO_CLIENTE      ("");                               
CP.setRAZON_SOCIAL_CLIENTE       ("");                               
CP.setTIPO_DOCUMENTO_CLIENTE     ("");                               
CP.setDIRECCION_CLIENTE          ("");                               
CP.setCIUDAD_CLIENTE             ("");                               
CP.setCOD_PAIS_CLIENTE           ("");                               
//=========================("");====DATOS EMPRESA==============
CP.setNRO_DOCUMENTO_EMPRESA      ("");                               
CP.setTIPO_DOCUMENTO_EMPRESA     ("");                               
CP.setNOMBRE_COMERCIAL_EMPRESA   ("");                               
CP.setCODIGO_UBIGEO_EMPRESA      ("");                               
CP.setDIRECCION_EMPRESA          ("");                               
CP.setDEPARTAMENTO_EMPRESA       ("");                               
CP.setPROVINCIA_EMPRESA          ("");                               
CP.setDISTRITO_EMPRESA           ("");                               
CP.setCODIGO_PAIS_EMPRESA        ("");                               
CP.setRAZON_SOCIAL_EMPRESA       ("");                               
CP.setUSUARIO_SOL_EMPRESA        ("");                               
CP.setPASS_SOL_EMPRESA           ("");                               
CP.setCONTRA_FIRMA               ("");                               
CP.setTIPO_PROCESO (1);                                            


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField t_1;
    // End of variables declaration//GEN-END:variables
}
